"""
lunar_dataloader.py
===================
PyTorch Dataset class for the Lunar MAE foundation model.
Reads the highly compressed .npz archive generated by extract_tiles_v2.py.
"""

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

class LunarNPZDataset(Dataset):
    def __init__(self, npz_path):
        """
        Initializes the dataset by loading the .npz archive into memory.
        
        Args:
            npz_path (str): Path to the lunar_tiles_v2.npz file.
        """
        print(f"Loading dataset from {npz_path} into RAM...")
        
        # Load the compressed numpy archive
        archive = np.load(npz_path)
        # archive = np.load(npz_path, allow_pickle=True)
        
        # Extract the 'tiles' array (Shape: [N, 224, 224], dtype: uint8)
        self.tiles = archive['tiles']
        
        print(f"Successfully loaded {len(self.tiles)} tiles.")

    def __len__(self):
        """Returns the total number of tiles in the dataset."""
        return len(self.tiles)

    def __getitem__(self, idx):
        """
        Fetches a single tile, restores its original float format, 
        and converts it to a PyTorch tensor.
        """
        # 1. Grab the 224x224 uint8 tile at the specified index
        tile_uint8 = self.tiles[idx]
        
        # 2. Convert to float32 and restore to the [0.0, 1.0] range
        tile_float = tile_uint8.astype(np.float32) / 255.0
        
        # 3. Add the channel dimension expected by PyTorch Conv2d/ViT layers
        # Converts shape from [224, 224] to [1, 224, 224]
        tile_expanded = np.expand_dims(tile_float, axis=0)
        
        # 4. Convert to a PyTorch tensor
        tile_tensor = torch.from_numpy(tile_expanded)
        
        return tile_tensor

# =========================================
# Quick Testing / Usage Example
# =========================================
if __name__ == "__main__":
    # Point this to your generated file
    dataset_path = "lunar_tiles_v2.npz"
    
    try:
        # Instantiate the dataset
        dataset = LunarNPZDataset(dataset_path)
        
        # Wrap it in a PyTorch DataLoader for batching and shuffling
        dataloader = DataLoader(
            dataset, 
            batch_size=64, 
            shuffle=True, 
            num_workers=2, 
            pin_memory=True # Speeds up transfer to GPU
        )
        
        # Fetch a single batch to verify shapes
        for batch in dataloader:
            print(f"\nBatch fetched successfully!")
            print(f"Batch Shape: {batch.shape}") # Expected: [64, 1, 224, 224]
            print(f"Batch Data Type: {batch.dtype}")
            print(f"Min Val: {batch.min().item():.3f}, Max Val: {batch.max().item():.3f}")
            break
            
    except FileNotFoundError:
        print(f"Could not find {dataset_path}. Please run extract_tiles_v2.py first.")